package GUI;

import GeneticAlgorithm.Genetic;
import GeneticAlgorithm.Generator;
import GeneticAlgorithm.tester;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Yosua Yuuta Bima P
 */
public class UserInterface extends javax.swing.JFrame {

    //100 1000 1 1 2 3 5 0.5 0.01
    public static String filePath = new String();
    public static Generator generator = new Generator();
    public static Genetic genetic = new Genetic(generator);

    private static final int SLEEP_TIME = 600000;

    /**
     * Creates new form GeneticAlgorithm
     */
    public UserInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        jLabel20 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jml_populasi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jml_generasi = new javax.swing.JTextField();
        crossover_type = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cross_rate = new javax.swing.JTextField();
        mut_rate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        view_hasil = new javax.swing.JTextArea();
        start_algen = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dosenPath = new javax.swing.JTextField();
        browseDosen = new javax.swing.JButton();
        browseJadwal = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jatah_dekan = new javax.swing.JTextField();
        jatah_tetap = new javax.swing.JTextField();
        jatah_kontrak = new javax.swing.JTextField();
        jatah_prodi = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jadwalPath = new javax.swing.JTextField();
        fileStatus = new javax.swing.JLabel();
        best_fitness = new javax.swing.JLabel();
        time_elapse = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        dekan_checker = new javax.swing.JLabel();
        prodi_checker = new javax.swing.JLabel();
        tetap_checker = new javax.swing.JLabel();
        kontrak_checker = new javax.swing.JLabel();
        populasi_checker = new javax.swing.JLabel();
        generasi_checker = new javax.swing.JLabel();
        cross_rate_checker = new javax.swing.JLabel();
        mut_rate_checker = new javax.swing.JLabel();
        export_button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        view_dosen = new javax.swing.JTextArea();

        jLabel16.setText("jLabel16");

        jLabel17.setText("jLabel17");

        jLabel18.setText("jLabel18");

        label1.setText("label1");

        jLabel20.setText("jLabel20");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jml_populasi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jml_populasi.setText("10");
        jml_populasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jml_populasiActionPerformed(evt);
            }
        });
        jml_populasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jml_populasiKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Jumlah Populasi");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Jumlah Generasi");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Crossover type");

        jml_generasi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jml_generasi.setText("100");
        jml_generasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jml_generasiActionPerformed(evt);
            }
        });
        jml_generasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jml_generasiKeyPressed(evt);
            }
        });

        crossover_type.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        crossover_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1-point", "2-point", "uniform" }));
        crossover_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crossover_typeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Crossover Rate");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Mutation Rate");

        cross_rate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cross_rate.setText("0.5");
        cross_rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cross_rateActionPerformed(evt);
            }
        });
        cross_rate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cross_rateKeyPressed(evt);
            }
        });

        mut_rate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mut_rate.setText("0.01");
        mut_rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mut_rateActionPerformed(evt);
            }
        });
        mut_rate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mut_rateKeyPressed(evt);
            }
        });

        view_hasil.setColumns(20);
        view_hasil.setRows(5);
        jScrollPane1.setViewportView(view_hasil);

        start_algen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        start_algen.setText("START");
        start_algen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_algenActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Best Fitness");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Process Time");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("File Jadwal Ujian");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("File Data Dosen");

        dosenPath.setText("files\\dosentest.csv");
        dosenPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosenPathActionPerformed(evt);
            }
        });

        browseDosen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        browseDosen.setText("Browse");
        browseDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseDosenActionPerformed(evt);
            }
        });

        browseJadwal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        browseJadwal.setText("Browse");
        browseJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseJadwalActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Jatah Kepala Prodi.");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Jatah Dosen Tetap");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Jatah Senat & Dekanat");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Jatah Dosen Kontrak");

        jatah_dekan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jatah_dekan.setText("1");
        jatah_dekan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jatah_dekanActionPerformed(evt);
            }
        });
        jatah_dekan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jatah_dekanKeyPressed(evt);
            }
        });

        jatah_tetap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jatah_tetap.setText("3");
        jatah_tetap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jatah_tetapActionPerformed(evt);
            }
        });
        jatah_tetap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jatah_tetapKeyPressed(evt);
            }
        });

        jatah_kontrak.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jatah_kontrak.setText("5");
        jatah_kontrak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jatah_kontrakActionPerformed(evt);
            }
        });
        jatah_kontrak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jatah_kontrakKeyPressed(evt);
            }
        });

        jatah_prodi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jatah_prodi.setText("2");
        jatah_prodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jatah_prodiActionPerformed(evt);
            }
        });
        jatah_prodi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jatah_prodiKeyPressed(evt);
            }
        });

        jLabel14.setText("____________________________________________________________________________________________");

        jLabel15.setText("___________________________________________________________________________________________");

        jadwalPath.setText("files\\FileJadwalPengawas.csv");
        jadwalPath.setAutoscrolls(false);
        jadwalPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jadwalPathActionPerformed(evt);
            }
        });

        fileStatus.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        fileStatus.setForeground(new java.awt.Color(255, 0, 0));
        fileStatus.setText("IDLE");

        best_fitness.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        best_fitness.setText("0.0");

        time_elapse.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time_elapse.setText("0");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("s");

        dekan_checker.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dekan_checker.setForeground(new java.awt.Color(255, 51, 0));
        dekan_checker.setText("(integer)");

        prodi_checker.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prodi_checker.setForeground(new java.awt.Color(255, 51, 51));
        prodi_checker.setText("(integer)");

        tetap_checker.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tetap_checker.setForeground(new java.awt.Color(255, 51, 51));
        tetap_checker.setText("(integer)");

        kontrak_checker.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kontrak_checker.setForeground(new java.awt.Color(255, 51, 51));
        kontrak_checker.setText("(integer)");

        populasi_checker.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        populasi_checker.setForeground(new java.awt.Color(255, 51, 51));
        populasi_checker.setText("(integer)");

        generasi_checker.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        generasi_checker.setForeground(new java.awt.Color(255, 51, 51));
        generasi_checker.setText("(integer)");

        cross_rate_checker.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cross_rate_checker.setForeground(new java.awt.Color(255, 51, 51));
        cross_rate_checker.setText("(float)");

        mut_rate_checker.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mut_rate_checker.setForeground(new java.awt.Color(255, 51, 51));
        mut_rate_checker.setText("(float)");

        export_button.setText("Export .csv");
        export_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                export_buttonActionPerformed(evt);
            }
        });

        view_dosen.setColumns(20);
        view_dosen.setRows(5);
        jScrollPane2.setViewportView(view_dosen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jatah_prodi, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jatah_dekan, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jatah_tetap, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jatah_kontrak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dekan_checker)
                                    .addComponent(prodi_checker)
                                    .addComponent(tetap_checker)
                                    .addComponent(kontrak_checker))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(548, 548, 548))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(68, 68, 68)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(start_algen, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(mut_rate, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                                    .addComponent(crossover_type, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jml_generasi, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jml_populasi, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cross_rate, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(87, 87, 87)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(populasi_checker)
                                                    .addComponent(generasi_checker)
                                                    .addComponent(cross_rate_checker)
                                                    .addComponent(mut_rate_checker)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(time_elapse)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(best_fitness)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(dosenPath, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                                            .addComponent(jadwalPath, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(browseJadwal)
                                            .addComponent(browseDosen)))
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(export_button, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(export_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jadwalPath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseJadwal))
                        .addGap(9, 9, 9)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dosenPath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseDosen))
                        .addGap(18, 18, 18)
                        .addComponent(fileStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jatah_dekan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dekan_checker))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jatah_prodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prodi_checker))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jatah_tetap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(tetap_checker))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jatah_kontrak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kontrak_checker))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jml_populasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(populasi_checker))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jml_generasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(generasi_checker))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(crossover_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cross_rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cross_rate_checker))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mut_rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mut_rate_checker)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(start_algen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(best_fitness, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel19)
                            .addComponent(time_elapse))
                        .addGap(72, 72, 72))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new UserInterface().setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }


    private void jml_populasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jml_populasiActionPerformed
        int jumlahPopulasi = Integer.parseInt(jml_populasi.getText());
        if (jumlahPopulasi < 2) {
            jml_populasi.setText("2");
        }
    }//GEN-LAST:event_jml_populasiActionPerformed

    private void start_algenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_algenActionPerformed
        tester runner = new tester();
        runner.mainGUI(jml_populasi.getText(), jml_generasi.getText(), jadwalPath.getText(), dosenPath.getText(),
                jatah_dekan.getText(), jatah_prodi.getText(), jatah_tetap.getText(), jatah_kontrak.getText(),
                crossover_type.getSelectedIndex(), Float.parseFloat(cross_rate.getText()), Float.parseFloat(mut_rate.getText()),
                view_hasil, view_dosen, time_elapse, best_fitness);
    }//GEN-LAST:event_start_algenActionPerformed

    private void mut_rateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mut_rateActionPerformed
        float mutationRate = Integer.parseInt(mut_rate.getText());
        if (mutationRate < 0) {
            mut_rate.setText("0");
        }
        if (mutationRate > 1) {
            mut_rate.setText("1");
        }
    }//GEN-LAST:event_mut_rateActionPerformed

    private void browseJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseJadwalActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        File selectedFile = fc.getSelectedFile();
        if (selectedFile != null) {
            this.filePath = selectedFile.getAbsolutePath();
            this.jadwalPath.setText(filePath);
            fileStatus.setText("File jadwal berhasil di import");
        } else {
            fileStatus.setText("File jadwal gagal di import");
        }
    }//GEN-LAST:event_browseJadwalActionPerformed

    private void jatah_dekanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jatah_dekanActionPerformed
        int jatahDekan = Integer.parseInt(jatah_dekan.getText());
        if (jatahDekan < 0) {
            jatah_dekan.setText("1");
        }
    }//GEN-LAST:event_jatah_dekanActionPerformed

    private void jatah_tetapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jatah_tetapActionPerformed
        int jatahTetap = Integer.parseInt(jatah_tetap.getText());
        if (jatahTetap < 0) {
            jatah_tetap.setText("1");
        }
    }//GEN-LAST:event_jatah_tetapActionPerformed

    private void jatah_kontrakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jatah_kontrakActionPerformed
        int jatahKontrak = Integer.parseInt(jatah_kontrak.getText());
        if (jatahKontrak < 0) {
            jatah_kontrak.setText("1");
        }
    }//GEN-LAST:event_jatah_kontrakActionPerformed

    private void jatah_prodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jatah_prodiActionPerformed
        int jatahProdi = Integer.parseInt(jatah_prodi.getText());
        if (jatahProdi < 0) {
            jatah_prodi.setText("1");
        }
    }//GEN-LAST:event_jatah_prodiActionPerformed

    private void browseDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseDosenActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        File selectedFile = fc.getSelectedFile();
        if (selectedFile != null) {
            this.filePath = selectedFile.getAbsolutePath();
            this.dosenPath.setText(filePath);
            fileStatus.setText("File daftar dosen berhasil di import");
        } else {
            fileStatus.setText("File daftar dosen gagal di import");
        }
    }//GEN-LAST:event_browseDosenActionPerformed

    private void dosenPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosenPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dosenPathActionPerformed

    private void jadwalPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadwalPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jadwalPathActionPerformed

    private void jml_generasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jml_generasiActionPerformed
        int jumlahGenerasi = Integer.parseInt(jml_generasi.getText());
        if (jumlahGenerasi < 0) {
            jml_generasi.setText("0");
        }
    }//GEN-LAST:event_jml_generasiActionPerformed

    private void cross_rateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cross_rateActionPerformed
        float crossRate = Integer.parseInt(cross_rate.getText());
        if (crossRate < 0) {
            cross_rate.setText("0");
        }
        if (crossRate > 1) {
            cross_rate.setText("1");
        }
    }//GEN-LAST:event_cross_rateActionPerformed

    private void jatah_dekanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jatah_dekanKeyPressed
        try {
            int jatahDekan = Integer.parseInt(jatah_dekan.getText());
            dekan_checker.setText("(integer)");

        } catch (NumberFormatException e) {
            dekan_checker.setText("Invalid number");
        }
    }//GEN-LAST:event_jatah_dekanKeyPressed

    private void jatah_prodiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jatah_prodiKeyPressed
        try {
            int jatahProdi = Integer.parseInt(jatah_prodi.getText());
            prodi_checker.setText("(integer)");
        } catch (NumberFormatException e) {
            prodi_checker.setText("Invalid number");
        }
    }//GEN-LAST:event_jatah_prodiKeyPressed

    private void jatah_tetapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jatah_tetapKeyPressed
        try {
            int jatahTetap = Integer.parseInt(jatah_tetap.getText());
            tetap_checker.setText("(integer)");
        } catch (NumberFormatException e) {
            tetap_checker.setText("Invalid number");
        }
    }//GEN-LAST:event_jatah_tetapKeyPressed

    private void jatah_kontrakKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jatah_kontrakKeyPressed
        try {
            int jatahKontrak = Integer.parseInt(jatah_kontrak.getText());
            kontrak_checker.setText("(integer)");
        } catch (NumberFormatException e) {
            kontrak_checker.setText("Invalid number");
        }
    }//GEN-LAST:event_jatah_kontrakKeyPressed

    private void jml_populasiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jml_populasiKeyPressed
        try {
            int jmlPopulasi = Integer.parseInt(jml_populasi.getText());
            populasi_checker.setText("(integer)");
        } catch (NumberFormatException e) {
            populasi_checker.setText("Invalid number");
        }
    }//GEN-LAST:event_jml_populasiKeyPressed

    private void jml_generasiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jml_generasiKeyPressed
        try {
            int jmlGenerasi = Integer.parseInt(jml_generasi.getText());
            generasi_checker.setText("(integer)");
        } catch (NumberFormatException e) {
            generasi_checker.setText("Invalid number");
        }
    }//GEN-LAST:event_jml_generasiKeyPressed

    private void cross_rateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cross_rateKeyPressed
        try {
            float crossRate = Float.parseFloat(cross_rate.getText());
            cross_rate_checker.setText("(float)");
        } catch (NumberFormatException e) {
            cross_rate_checker.setText("Invalid number");
        }
    }//GEN-LAST:event_cross_rateKeyPressed

    private void mut_rateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mut_rateKeyPressed
        try {
            float mutRate = Float.parseFloat(mut_rate.getText());
            mut_rate_checker.setText("(float)");
        } catch (NumberFormatException e) {
            mut_rate_checker.setText("Invalid number");
        }
    }//GEN-LAST:event_mut_rateKeyPressed

    private void export_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_export_buttonActionPerformed
        tester.toCSV(genetic, generator);
    }//GEN-LAST:event_export_buttonActionPerformed

    private void crossover_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crossover_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crossover_typeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel best_fitness;
    private javax.swing.JButton browseDosen;
    private javax.swing.JButton browseJadwal;
    private javax.swing.JTextField cross_rate;
    private javax.swing.JLabel cross_rate_checker;
    private javax.swing.JComboBox<String> crossover_type;
    private javax.swing.JLabel dekan_checker;
    private javax.swing.JTextField dosenPath;
    private javax.swing.JButton export_button;
    private javax.swing.JLabel fileStatus;
    private javax.swing.JLabel generasi_checker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jadwalPath;
    private javax.swing.JTextField jatah_dekan;
    private javax.swing.JTextField jatah_kontrak;
    private javax.swing.JTextField jatah_prodi;
    private javax.swing.JTextField jatah_tetap;
    private javax.swing.JTextField jml_generasi;
    private javax.swing.JTextField jml_populasi;
    private javax.swing.JLabel kontrak_checker;
    private java.awt.Label label1;
    private javax.swing.JTextField mut_rate;
    private javax.swing.JLabel mut_rate_checker;
    private javax.swing.JLabel populasi_checker;
    private javax.swing.JLabel prodi_checker;
    private javax.swing.JButton start_algen;
    private javax.swing.JLabel tetap_checker;
    private javax.swing.JLabel time_elapse;
    private javax.swing.JTextArea view_dosen;
    private javax.swing.JTextArea view_hasil;
    // End of variables declaration//GEN-END:variables
}
